CREATE DATABASE SIMPLEMARKET
GO
USE SIMPLEMARKET
GO



CREATE TABLE USERS(
USERNAME VARCHAR(32) PRIMARY KEY,
PASSWORD VARCHAR(50) NOT NULL,
ROLES VARCHAR(10) NOT NULL DEFAULT 'EMPLOYEE'
)
GO
CREATE TABLE PRODUCTS(
PRODUCT_ID VARCHAR(10) PRIMARY KEY,
PRODUCT_NAME NVARCHAR(100) NOT NULL,
PRODUCT_DESCRIPTION NVARCHAR(MAX) NOT NULL DEFAULT N'Chưa có miêu tả',
PRODCUT_PRICE INT NOT NULL DEFAULT 0,
)
go
CREATE TABLE CART_DETAIL(
CARTDETAIL_ID INT IDENTITY PRIMARY KEY,
USERNAME VARCHAR(32) NOT NULL FOREIGN KEY REFERENCES USERS(USERNAME),
PRODUCT_ID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES PRODUCTS(PRODUCT_ID),
CARTDETAIL_COUNT INT NOT NULL DEFAULT 1
)
GO
CREATE TABLE ORDERS(
ORDER_ID INT IDENTITY PRIMARY KEY,
USERNAME VARCHAR(32) NOT NULL FOREIGN KEY REFERENCES USERS(USERNAME),
ORDER_PAYMETHOD VARCHAR(10) NOT NULL DEFAULT 'COD',
ORDER_CREATEDTIME DATETIME NOT NULL DEFAULT GETDATE(),
 ORDER_STATUS NVARCHAR(50) NOT NULL DEFAULT N'ĐANG CHỜ XÁC NHẬN'
)
GO
CREATE TABLE ORDER_DETAIL(
ORDERDETAIL_ID INT IDENTITY PRIMARY KEY,
ORDER_ID INT FOREIGN KEY REFERENCES ORDERS(ORDER_ID),
PRODUCT_ID VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES PRODUCTS(PRODUCT_ID),
ORDERDETAIL_COUNT INT NOT NULL DEFAULT 1
)



GO
INSERT INTO PRODUCTS VALUES ('00005',N'sẢN PHẨM 1', N'kHÔNG THÍCH MIÊU TẢ', 1000)
INSERT INTO PRODUCTS VALUES ('00006',N'sẢN PHẨM 2', N'SDAFSDFSD', 2000)
INSERT INTO PRODUCTS VALUES ('00007',N'sẢN PHẨM 3', N'vIỆT nAM lÀO CAMPUCHIA', 3000)
INSERT INTO PRODUCTS VALUES ('00008',N'sẢN PHẨM 4', N'THỰC TẬP CHUYÊN MÔN', 5000)
INSERT INTO PRODUCTS VALUES ('00009',N'sẢN PHẨM 5', N'ALO ALO ALO 124234543SDJFGDSJDG TRÀN DÂN', 6000)

--delete from CART_DETAIL
--delete from ORDER_DETAIL
--delete from orders
--delete from PRODUCTS
--drop table ORDER_DETAIL
--drop table ORDERS
--drop table CART_DETAIL
--drop table PRODUCTS